import { type Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "~/styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const regarn = localFont({
  src: "../../public/assets/font/Regarn-Bold.ttf",
  display: "swap",
  variable: "--font-regarn",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${regarn.variable} ${inter.variable} `}>
      <body>{children}</body>
    </html>
  );
}
